"""`nav db schema` — print the current database schema."""

import click

from navtool.db import MEMORY_DB, get_connection


@click.command("schema")
def db_schema():
    """Print the current database schema.

    Generated by building a fresh in-memory database from the migration chain and
    dumping its definitions, so it always reflects the real schema — there is no
    hand-maintained schema file that could drift.
    """
    conn = get_connection(MEMORY_DB)
    try:
        rows = conn.execute(
            "SELECT sql FROM sqlite_master WHERE sql IS NOT NULL "
            "ORDER BY type = 'index', name"
        ).fetchall()
    finally:
        conn.close()
    for (sql,) in rows:
        click.echo(f"{sql};")
