#!/usr/bin/python2.7
import getopt
import os
import sys
import shutil

LONG_HELP = True
SHORT_HELP = False

DONT_PRINT_KEYS = False
DO_PRINT_KEYS = True

STAGE_SET = "STAGE_SET"

class colors:
    PINK =      '\033[95m'
    BLUE =      '\033[94m'
    CYAN =      '\033[94m'
    GREEN =     '\033[92m'
    RED =       '\033[91'
    YELLOW =    '\033[93m'
    NONE =      '\033[0m'

def main():
    flags = sys.argv[1:]

    try:
        opts, args = getopt.getopt(flags, "hH", ["help", "Help", "showConfig", "listKeys", "listSets=", "usingSets", "canAddSet=", "newSet=", "makeKey=", "rmKey=", "rmSet=", "getKeyTarget="])
    except:
        error("could not parse flags")
        exit(1)

    for o,a in opts:
        if o == "--help": 
            # Print Short help
            help(SHORT_HELP)
            exit(0)

        elif o == "--Help": 
            # Print Long help
            help(LONG_HELP)
            exit(0)

        elif o == "--showConfig":
            showConfig()
            exit(0)

        elif o == "--listKeys":
            listKeysInPath()
            exit(0)
        
        elif o == "--listSets":
            if a == "with-keys":
                listAllSets(DO_PRINT_KEYS)
            elif a == "without-keys":
                listAllSets(DONT_PRINT_KEYS)
            else:
                print "Unrecognized argument to --listSets: %s" %(a)
                exit(1)

        elif o == "--usingSets":
            listSetsInPath()
            exit(0)

        elif o == "--newSet":
            # Make a new set
            makeNewSet(a)
            exit(0)

        elif o == "--canAddSet":
            argSplit = a.split('::', 1)
            if len(argSplit) is not 2:
                error("navtool-util: invalid input: %s" %(a))
                exit(1)
            setName = argSplit[0]
            position = argSplit[1]
            canAddSet(setName, position)

        elif o == "--makeKey":
            # Make a new key in a set (STAGE_SET by default)
            argSplit = a.split('::', 2)
            if len(argSplit) is not 3: 
                error("navtool-util: invalid input: %s" %a)
                exit(1)
            setName = argSplit[0]
            key = argSplit[1]
            path = argSplit[2]
            makeKeyInSet(key, path, setName)

        elif o == "--rmKey":
            # remove a key in your path. Default is to remove the first occurance if
            # setName is %FIRST_OCCURANCE%
            argSplit = a.split('::', 1)
            if len(argSplit) is not 2: 
                error("navtool-util: invalid input: %s" %a)
                exit(1)
            setName = argSplit[0]
            if setName == "%FIRST_OCCURANCE%":
                setName = None
            key = argSplit[1]
            removeKey(key, setName)

        elif o == "--rmSet":
            # Remove a set from the sets directory
            removeSet(a)
            exit(0)

        elif o == "--getKeyTarget":
            print(getKeyTarget(a))
            exit(0)

        else:
            error("Unrecognized flag: %s" %(o))
            exit(1)


def longHelp():
    print "  --help                    Show short help menu [-h]"
    print "  --Help                    Show long help menu [-H]" 
    print "  --key KEY SET             Make a new key with NAME to the SET [-k]"
    print "                              - SET is optional -> default is STAGE_SET"
    print "  --set NAME                Make a new empty set referenced by NAME [-s]"
    print "  --include SET             Add SET to the path so its keys can be used [-i]"
    print "                              - Default puts at front of path, use --back after SET to put at back"
    print "  --rmKey KEY SET           Delete the key with NAME from the SET [-r]"
    print "                              - SET is optional -> default remove first key in NAVTOOL_PATH"
    print "  --rmSet SET               Delete the set with NAME [-R]"
    print "  --listKeys                List the keys in the navtool's path [-l]"
    print "  --listSets                List the sets that are available to navtool [-L]"
    print "                              - Optional args to include keys: with-keys without-keys"
    print "  --usingSets               List the sets in the current navtool's path"
    print "  --showConfig              Show the configuration for navtool"


def help(doLongHelp):
    print "nav [NAV_KEY] [--help] [--Help] [--key KEY_NAME (SET_NAME)] [--set NAME] [--include SET] [--rmKey KEY (SET)] [--rmSet SET] [--listKeys] [--listSets] [--usingSets] [--showConfig]"
    if doLongHelp:
        longHelp()


def error(message):
    print "ERROR: %s" %(message)


def success(message):
    print "SUCCESS: %s" %(message)


def showConfig():
    path = os.getenv("NAVTOOL_PATH")
    root = os.getenv("NAVTOOL_ROOT")
    print "%sPath:%s  %s" %(colors.BLUE, colors.NONE, path)
    print "%sRoot:%s  %s" %(colors.BLUE, colors.NONE, root)

def getKeyTarget(targetKey):
    navtoolPath = os.getenv('NAVTOOL_PATH')
    allSetsDir = "%s/sets" %os.getenv('NAVTOOL_ROOT')

    # Loop through the sets in the order that they show up 
    # in the path variable and return the first key we find
    sets = navtoolPath.split(':')
    for s in sets:
        setPath = "%s/%s" %(allSetsDir, s)
        if not os.path.isdir(setPath):
            continue
        keys = os.listdir(setPath)
        for k in keys:
            if k == targetKey:
                return os.readlink("%s/%s" %(setPath, k))

    # If user passed a real path they can navigate to it
    if os.path.isdir(targetKey):
        return targetKey

    # If user passed a real file, they can navigate to its location
    if os.path.isfile(targetKey):
        pathOfFile = os.path.dirname(os.path.abspath(targetKey))
        return pathOfFile

    # Return empty path
    return ""


def listKeysInPath():
    navtoolPath = os.getenv('NAVTOOL_PATH')
    allSetsDir = "%s/sets" %os.getenv('NAVTOOL_ROOT')

    # Loop through the sets in the order that they show up
    sets = navtoolPath.split(':')
    for i, s in enumerate(sets):
        setPath = "%s/%s" %(allSetsDir, s)
        if not os.path.isdir(setPath):
            continue
        keys = os.listdir(setPath)
        longestKeyLen = 0
        for k in keys:
            if len(k) > longestKeyLen:
                longestKeyLen = len(k)
        for k in keys:
            target =  os.readlink("%s/%s" %(setPath, k))
            print " %s%s%s::%s%s%s -> %s%s%s" %(colors.PINK, s, colors.NONE, colors.BLUE, padStrRight(k, longestKeyLen), colors.NONE, colors.YELLOW, target, colors.NONE)
        if i < len(sets)-1:
            print ""


def listAllSets(printKeys):
    navtoolPath = os.getenv('NAVTOOL_PATH')
    allSetsDir = "%s/sets" %os.getenv('NAVTOOL_ROOT')
    if not os.path.isdir(allSetsDir):
        print("There are no sets currently defined.")
        return;

    # Loop through the sets in the order that they show up
    sets = os.listdir(allSetsDir)
    for s in sets:
        setPath = "%s/%s" %(allSetsDir, s)
        if not os.path.isdir(setPath):
            continue
        else:
            print " %s%s%s" %(colors.PINK, s, colors.NONE)
            if printKeys:
                keys = os.listdir(setPath)
                longestKeyLen = 0
                for k in keys:
                    if len(k) > longestKeyLen:
                        longestKeyLen = len(k)
                for k in keys:
                    target =  os.readlink("%s/%s" %(setPath, k))
                    print "   %s%s%s -> %s%s%s" %(colors.BLUE, padStrRight(k, longestKeyLen), colors.NONE, colors.YELLOW, target, colors.NONE)


def listSetsInPath():
    navtoolPath = os.getenv('NAVTOOL_PATH')
    allSetsDir = "%s/sets" %os.getenv('NAVTOOL_ROOT')

    # Loop through the sets in the order that they show up
    sets = navtoolPath.split(':')
    for s in sets:
        print "%s%s%s" %(colors.PINK, s, colors.NONE)


def makeNewSet(name):
    allSetsDir = "%s/sets" %(os.getenv('NAVTOOL_ROOT'))
    if not os.path.isdir(allSetsDir):
        os.mkdir(allSetsDir)

    newSet = "%s/%s" %(allSetsDir, name)
    if not os.path.isdir(newSet):
        os.mkdir(newSet)
        print "Made new set [%s%s%s]." %(colors.YELLOW, name, colors.NONE)
        exit(0)
    else:
        error("set already exists [%s%s%s]." %(colors.YELLOW, name, colors.NONE))
        exit(1)
    

def makeKeyInSet(key, target, setName):
    allSetsDir = "%s/sets" %(os.getenv('NAVTOOL_ROOT'))
    if not os.path.isdir(allSetsDir):
        os.mkdir(allSetsDir)

    setDir = "%s/%s" %(allSetsDir, setName)

    # If the set is the STAGE_SET then make it if it doesnt already exist
    if setName == STAGE_SET:
        if not os.path.isdir(setDir):
            os.mkdir(setDir)
    else:
        if not os.path.isdir(setDir):
            error("set [%s] does not exist" %(setName))
            exit(1)
        
    # Add the key to the set if it doesnt exist yet
    keyPath = "%s/%s" %(setDir, key)
    if os.path.islink(keyPath):
        error("key [%s] already exists in set [%s]" %(key, setName))
        exit(1)
    else:
        print("Added new key [%s%s%s] to set [%s%s%s]." %(colors.YELLOW, key, colors.NONE, colors.YELLOW, setName, colors.NONE))
        os.symlink(target, keyPath)
        exit(0)


# -R --rmSet
def removeSet(name):
    allSetsDir = "%s/sets" %os.getenv('NAVTOOL_ROOT')
    setPath = "%s/%s" %(allSetsDir, name)
    if os.path.isdir(setPath):
        Y_or_N = raw_input('Are you sure you want to delete the set [%s%s%s]: [y/n]' %(colors.YELLOW, name, colors.NONE))
        if Y_or_N == "y" or Y_or_N == "Y" or Y_or_N == "yes":
            shutil.rmtree(setPath)
            print "Removed set: %s" %(name)
        else:
            print "Exiting."
    else:
        error("Set does not exist [%s%s%s]." %(colors.YELLOW, name, colors.NONE))
    

# -r --rmKey
def removeKey(key, setName):
    navtoolPath = os.getenv('NAVTOOL_PATH')
    allSetsDir = "%s/sets" %os.getenv('NAVTOOL_ROOT')

    removedKey = False
    if setName is None:
        # Loop through the sets in the order that they show up in the path
        # and remove the first occurance of the key
        sets = navtoolPath.split(':')
        for s in sets:
            setPath = "%s/%s" %(allSetsDir, s)
            if not os.path.isdir(setPath):
                continue
            keys = os.listdir(setPath)
            for k in keys:
                if k == key:
                    keyPath = "%s/%s" %(setPath, k)
                    if os.path.islink(keyPath):
                        Y_or_N = raw_input('Are you sure you want to delete key [%s%s%s] in set [%s%s%s]: [y/n]: ' %(colors.YELLOW, k, colors.NONE, colors.YELLOW, s, colors.NONE))
                        if Y_or_N == "y" or Y_or_N == "Y" or Y_or_N == "yes":
                            os.remove(keyPath)
                            print "Removed key [%s] in set [%s]" %(k, s)
                            removedKey= True
                            break
                        else:
                            print "Exiting."
                            exit(0)
            if removedKey:
                break
    else:
        setPath = "%s/%s" %(allSetsDir, setName)
        if not os.path.isdir(setPath):
            error('specified set does not exist %s' %(setName))
        else:
            keys = os.listdir(setPath)
            for k in keys:
                if k == key:
                    keyPath = "%s/%s" %(setPath, k)
                    if os.path.islink(keyPath):
                        Y_or_N = raw_input('Are you sure you want to delete key [%s%s%s] in set [%s%s%s]: [y/n]: ' %(colors.YELLOW, k, colors.NONE, colors.YELLOW, setName, colors.NONE))
                        if Y_or_N == "y" or Y_or_N == "Y" or Y_or_N == "yes":
                            os.remove(keyPath)
                            print "Removed key [%s] in set [%s]" %(k, setName)
                            removedKey= True
                            break
                        else:
                            print "Exiting."
                            exit(0)

    # Check if we removed the key from the set
    if not removedKey:
        error('could not find key [%s] in your NAVTOOL_PATH' %(key))


# -i --include
def canAddSet(setName, position):
    navtoolPath = os.getenv('NAVTOOL_PATH')
    navtoolRoot = os.getenv('NAVTOOL_ROOT')
    pathSplit = navtoolPath.split(':')
    setPath = "%s/sets/%s" %(navtoolRoot, setName)

    if not os.path.isdir(setPath):
            # Cant add a set that doesnt exist
            print 'Set [%s%s%s] does not exist!' %(colors.YELLOW, setName, colors.NONE)
            exit(1)

    for currentSetName in pathSplit:
        # Check if the set already exists in the path
        if currentSetName == setName:
            print 'Set [%s%s%s] is already in your path!' %(colors.YELLOW, setName, colors.NONE)
            exit(1)

    #TODO: Look for keys that will be overshadowed to provide errors

    # Success
    exit(0)


def padStrRight(s, n):
    while len(s) < n:
        s = "%s " %s
    return s

if __name__ == "__main__":
    main()

